### ISSUE TITLE
本番環境で発生しているSprockets::Rails::Helper::AssetNotFoundを解消する

### ISSUE THREAD

**Issue by Kassy0220** [Kassy0220/fjord-minutes#231]
#230 をデプロイした際、本番環境で以下のエラーが発生した。
このエラーを解消する。

```
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537604&selected=1802745263984537604) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537604&selected=1802745263984537604) E, [2024-12-09T11:53:06.579595 #2] ERROR -- : [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537604&selected=1802745263984537604)]   
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537605&selected=1802745263984537605) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537605&selected=1802745263984537605) [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537605&selected=1802745263984537605)] ActionView::Template::Error (The asset "ogp_image" is not present in the asset pipeline.
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537606&selected=1802745263984537606) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537606&selected=1802745263984537606) ):
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537607&selected=1802745263984537607) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537607&selected=1802745263984537607) [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537607&selected=1802745263984537607)] 
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537608&selected=1802745263984537608) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537608&selected=1802745263984537608) Causes:
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537609&selected=1802745263984537609) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537609&selected=1802745263984537609) [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537609&selected=1802745263984537609)] Sprockets::Rails::Helper::AssetNotFound (The asset "ogp_image" is not present in the asset pipeline.
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537610&selected=1802745263984537610) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537610&selected=1802745263984537610) )
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537611&selected=1802745263984537611) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537611&selected=1802745263984537611) [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537611&selected=1802745263984537611)]     1: <% set_meta_tags(build_meta_tags(title: 'ダッシュボード', description: 'ダッシュボードページです。')) %>
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537612&selected=1802745263984537612) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537612&selected=1802745263984537612) [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537612&selected=1802745263984537612)]     2: <div class="w-full">
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537613&selected=1802745263984537613) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537613&selected=1802745263984537613) [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537613&selected=1802745263984537613)]     3:   <h1 class="font-bold text-4xl text-center mb-8">管理ページ</h1>
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537614&selected=1802745263984537614) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537614&selected=1802745263984537614) [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537614&selected=1802745263984537614)]     4: 
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537615&selected=1802745263984537615) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537615&selected=1802745263984537615) [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537615&selected=1802745263984537615)]   
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537616&selected=1802745263984537616) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537616&selected=1802745263984537616) [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537616&selected=1802745263984537616)] app/helpers/application_helper.rb:16:in `build_meta_tags'
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537617&selected=1802745263984537617) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537617&selected=1802745263984537617) [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537617&selected=1802745263984537617)] app/views/home/admin_dashboard.html.erb:1
Dec 09 03:53:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745263984537618&selected=1802745263984537618) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1802745263984537618&selected=1802745263984537618) [[a94bab40-3f79-4baa-99cf-aa4e7cb0188c](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22a94bab40-3f79-4baa-99cf-aa4e7cb0188c%22&focus=1802745263984537618&selected=1802745263984537618)] app/controllers/home_controller.rb:9:in `index'
Dec 09 03:53:07 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1802745265112846339&selected=1802745265112846339) [heroku/router](https://my.papertrailapp.com/events?q=program%3Aheroku%2Frouter&focus=1802745265112846339&selected=1802745265112846339) at=info method=GET path="/favicon.ico" host=fjord-minutes-eded74419c61.herokuapp.com request_id=[34fb59df-17c1-4d6a-8061-21308b74ea04](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%2234fb59df-17c1-4d6a-8061-21308b74ea04%22&focus=1802745265112846339&selected=1802745265112846339) fwd="[111.239.179.227](https://my.papertrailapp.com/systems/fjord-minutes/events?q=%22111.239.179.227%22&focus=1802745265112846339&selected=1802745265112846339)" dyno=web.1 connect=0ms service=4ms status=404 bytes=1966 protocol=https
```

**Comment by Kassy0220** [comment]
本番環境で発生していたエラーの解消を確認できたため、このIssueをクローズします。
