### ISSUE TITLE
本番環境で発生しているエラー(`Zeitwerk::NameError`)を解消する

### ISSUE THREAD

**Issue by Kassy0220** [Kassy0220/fjord-minutes#82]
本番環境で次のエラーが発生しているので、解消する。

エラーログ。
```
Oct 17 12:35:59 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655195651031044&selected=1783655195651031044) [heroku/web.1](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fweb.1&focus=1783655195651031044&selected=1783655195651031044) State changed from crashed to starting
Oct 17 12:36:05 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655218073956372&selected=1783655218073956372) [heroku/web.1](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fweb.1&focus=1783655218073956372&selected=1783655218073956372) Starting process with command `bundle exec puma -C config/puma.rb`
Oct 17 12:36:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655222523879424&selected=1783655222523879424) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655222523879424&selected=1783655222523879424) Puma starting in single mode...
Oct 17 12:36:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655222523879425&selected=1783655222523879425) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655222523879425&selected=1783655222523879425) * Puma version: 6.4.3 (ruby 3.3.5-p100) ("The Eagle of Durango")
Oct 17 12:36:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655222523879426&selected=1783655222523879426) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655222523879426&selected=1783655222523879426) *  Min threads: 3
Oct 17 12:36:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655222523879427&selected=1783655222523879427) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655222523879427&selected=1783655222523879427) *  Max threads: 3
Oct 17 12:36:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655222523879428&selected=1783655222523879428) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655222523879428&selected=1783655222523879428) *  Environment: production
Oct 17 12:36:06 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655222523879429&selected=1783655222523879429) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655222523879429&selected=1783655222523879429) *          PID: 2
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655229981454337&selected=1783655229981454337) [heroku/web.1](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fweb.1&focus=1783655229981454337&selected=1783655229981454337) State changed from starting to crashed
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598151&selected=1783655230094598151) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598151&selected=1783655230094598151) ! Unable to load application: Zeitwerk::NameError: expected file /app/vendor/bundle/ruby/3.3.0/gems/devise-4.9.4/app/mailers/devise/mailer.rb to define constant Devise::Mailer, but didn't
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598152&selected=1783655230094598152) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598152&selected=1783655230094598152) bundler: failed to load command: puma (/app/vendor/bundle/ruby/3.3.0/bin/puma)
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598153&selected=1783655230094598153) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598153&selected=1783655230094598153) /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/callbacks.rb:32:in `on_file_autoloaded': expected file /app/vendor/bundle/ruby/3.3.0/gems/devise-4.9.4/app/mailers/devise/mailer.rb to define constant Devise::Mailer, but didn't (Zeitwerk::NameError)
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598155&selected=1783655230094598155) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598155&selected=1783655230094598155)       raise Zeitwerk::NameError.new(msg, cref.cname)
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598156&selected=1783655230094598156) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598156&selected=1783655230094598156)       ^^^^^
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598157&selected=1783655230094598157) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598157&selected=1783655230094598157) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:27:in `require'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598158&selected=1783655230094598158) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598158&selected=1783655230094598158) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/cref.rb:91:in `const_get'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598159&selected=1783655230094598159) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598159&selected=1783655230094598159) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/cref.rb:91:in `get'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598160&selected=1783655230094598160) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598160&selected=1783655230094598160) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:173:in `block in actual_eager_load_dir'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598161&selected=1783655230094598161) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598161&selected=1783655230094598161) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/helpers.rb:47:in `block in ls'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598162&selected=1783655230094598162) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598162&selected=1783655230094598162) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/helpers.rb:25:in `each'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598163&selected=1783655230094598163) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598163&selected=1783655230094598163) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/helpers.rb:25:in `ls'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598164&selected=1783655230094598164) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598164&selected=1783655230094598164) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:168:in `actual_eager_load_dir'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598165&selected=1783655230094598165) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598165&selected=1783655230094598165) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598166&selected=1783655230094598166) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598166&selected=1783655230094598166) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:16:in `each'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598167&selected=1783655230094598167) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598167&selected=1783655230094598167) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598168&selected=1783655230094598168) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598168&selected=1783655230094598168) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598169&selected=1783655230094598169) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598169&selected=1783655230094598169) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598170&selected=1783655230094598170) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598170&selected=1783655230094598170) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader.rb:413:in `block in eager_load_all'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598171&selected=1783655230094598171) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598171&selected=1783655230094598171) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader.rb:411:in `each'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598172&selected=1783655230094598172) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598172&selected=1783655230094598172) 	from /app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/loader.rb:411:in `eager_load_all'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598173&selected=1783655230094598173) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598173&selected=1783655230094598173) 	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/application/finisher.rb:80:in `block in <module:Finisher>'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598174&selected=1783655230094598174) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598174&selected=1783655230094598174) 	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/initializable.rb:32:in `instance_exec'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230094598175&selected=1783655230094598175) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230094598175&selected=1783655230094598175) 	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/initializable.rb:32:in `run'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792448&selected=1783655230098792448) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792448&selected=1783655230098792448) 	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792449&selected=1783655230098792449) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792449&selected=1783655230098792449) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792450&selected=1783655230098792450) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792450&selected=1783655230098792450) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792451&selected=1783655230098792451) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792451&selected=1783655230098792451) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792452&selected=1783655230098792452) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792452&selected=1783655230098792452) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792453&selected=1783655230098792453) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792453&selected=1783655230098792453) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/tsort.rb:350:in `each'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792454&selected=1783655230098792454) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792454&selected=1783655230098792454) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/tsort.rb:350:in `call'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792455&selected=1783655230098792455) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792455&selected=1783655230098792455) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792456&selected=1783655230098792456) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792456&selected=1783655230098792456) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792457&selected=1783655230098792457) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792457&selected=1783655230098792457) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792458&selected=1783655230098792458) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792458&selected=1783655230098792458) 	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/initializable.rb:60:in `run_initializers'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792459&selected=1783655230098792459) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792459&selected=1783655230098792459) 	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/application.rb:435:in `initialize!'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792460&selected=1783655230098792460) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792460&selected=1783655230098792460) 	from /app/config/environment.rb:5:in `<top (required)>'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792461&selected=1783655230098792461) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792461&selected=1783655230098792461) 	from config.ru:3:in `require_relative'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792462&selected=1783655230098792462) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792462&selected=1783655230098792462) 	from config.ru:3:in `block (2 levels) in <top (required)>'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792463&selected=1783655230098792463) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792463&selected=1783655230098792463) 	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:108:in `eval'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792464&selected=1783655230098792464) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792464&selected=1783655230098792464) 	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:108:in `new_from_string'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792465&selected=1783655230098792465) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792465&selected=1783655230098792465) 	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:97:in `load_file'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792466&selected=1783655230098792466) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792466&selected=1783655230098792466) 	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/builder.rb:67:in `parse_file'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792467&selected=1783655230098792467) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792467&selected=1783655230098792467) 	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/configuration.rb:368:in `load_rackup'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792468&selected=1783655230098792468) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792468&selected=1783655230098792468) 	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/configuration.rb:290:in `app'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792469&selected=1783655230098792469) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792469&selected=1783655230098792469) 	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/runner.rb:162:in `load_and_bind'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792470&selected=1783655230098792470) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792470&selected=1783655230098792470) 	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/single.rb:44:in `run'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792471&selected=1783655230098792471) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792471&selected=1783655230098792471) 	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/launcher.rb:194:in `run'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792472&selected=1783655230098792472) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792472&selected=1783655230098792472) 	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/cli.rb:75:in `run'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792473&selected=1783655230098792473) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792473&selected=1783655230098792473) 	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/bin/puma:10:in `<top (required)>'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792474&selected=1783655230098792474) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792474&selected=1783655230098792474) 	from /app/vendor/bundle/ruby/3.3.0/bin/puma:25:in `load'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792475&selected=1783655230098792475) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792475&selected=1783655230098792475) 	from /app/vendor/bundle/ruby/3.3.0/bin/puma:25:in `<top (required)>'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792476&selected=1783655230098792476) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792476&selected=1783655230098792476) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792477&selected=1783655230098792477) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792477&selected=1783655230098792477) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792478&selected=1783655230098792478) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792478&selected=1783655230098792478) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792479&selected=1783655230098792479) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792479&selected=1783655230098792479) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/bundler/cli.rb:455:in `exec'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792480&selected=1783655230098792480) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792480&selected=1783655230098792480) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792481&selected=1783655230098792481) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792481&selected=1783655230098792481) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792482&selected=1783655230098792482) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792482&selected=1783655230098792482) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792483&selected=1783655230098792483) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792483&selected=1783655230098792483) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792484&selected=1783655230098792484) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792484&selected=1783655230098792484) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792485&selected=1783655230098792485) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792485&selected=1783655230098792485) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/bundler/cli.rb:29:in `start'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792486&selected=1783655230098792486) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792486&selected=1783655230098792486) 	from /app/vendor/ruby-3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.16/exe/bundle:28:in `block in <top (required)>'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792487&selected=1783655230098792487) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792487&selected=1783655230098792487) 	from /app/vendor/ruby-3.3.5/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792488&selected=1783655230098792488) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792488&selected=1783655230098792488) 	from /app/vendor/ruby-3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.16/exe/bundle:20:in `<top (required)>'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792489&selected=1783655230098792489) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792489&selected=1783655230098792489) 	from /app/bin/bundle:108:in `load'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230098792490&selected=1783655230098792490) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1783655230098792490&selected=1783655230098792490) 	from /app/bin/bundle:108:in `<main>'
Oct 17 12:36:08 [fjord-minutes](https://my.papertrailapp.com/systems/fjord-minutes/events?focus=1783655230145056774&selected=1783655230145056774) [heroku/web.1](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fweb.1&focus=1783655230145056774&selected=1783655230145056774) Process exited with status 1
```

**Comment by Kassy0220** [comment]
本番環境で発生していたエラーの解消が確認できたため、このIssueをクローズします。
