### ISSUE TITLE
開発環境で発生しているエラー(`ActionView::Template::Error`)を解消する。

### ISSUE THREAD

**Issue by Kassy0220** [Kassy0220/fjord-minutes#83]
開発環境で`bin/dev`でサーバーを起動すると、次のエラーが発生する。
このエラーを解消する。

![FD4C072E-F4DA-47A1-9BE5-4A7C900CEA18](https://github.com/user-attachments/assets/d465cd1c-e93c-431c-b0ea-5595e993a907)

エラーログ。
```
07:53:16 web.1  | Started GET "/" for 127.0.0.1 at 2024-10-18 07:53:16 +0900
07:53:16 web.1  |   ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
07:53:16 web.1  | Processing by HomeController#index as HTML
07:53:16 web.1  |   Rendering layout layouts/application.html.erb
07:53:16 web.1  |   Rendering home/index.html.erb within layouts/application
07:53:16 web.1  |   Course Load (0.6ms)  SELECT "courses".* FROM "courses" ORDER BY "courses"."id" ASC
07:53:16 web.1  |   ↳ app/views/home/index.html.erb:10
07:53:16 web.1  |   Course Load (0.4ms)  SELECT "courses".* FROM "courses"
07:53:16 web.1  |   ↳ app/views/home/index.html.erb:22
07:53:16 web.1  |   Rendered home/index.html.erb within layouts/application (Duration: 49.5ms | GC: 1.7ms)
07:53:17 web.1  |   Rendered layout layouts/application.html.erb (Duration: 505.5ms | GC: 16.7ms)
07:53:17 web.1  | Completed 500 Internal Server Error in 530ms (ActiveRecord: 27.1ms (2 queries, 0 cached) | GC: 26.4ms)
07:53:17 web.1  | 
07:53:17 web.1  | 
07:53:17 web.1  |   
07:53:17 web.1  | ActionView::Template::Error (Multiple files with the same output path cannot be linked ("application.css")
07:53:17 web.1  | In "/Users/kashiyamashintarou/Working/HomeGrownService/FjordMinutes/app/assets/config/manifest.js" these files were linked:
07:53:17 web.1  |   - /Users/kashiyamashintarou/Working/HomeGrownService/FjordMinutes/app/assets/stylesheets/application.css
07:53:17 web.1  |   - /Users/kashiyamashintarou/Working/HomeGrownService/FjordMinutes/app/assets/builds/application.css
07:53:17 web.1  | ):
07:53:17 web.1  | 
07:53:17 web.1  | Causes:
07:53:17 web.1  | Sprockets::DoubleLinkError (Multiple files with the same output path cannot be linked ("application.css")
07:53:17 web.1  | In "/Users/kashiyamashintarou/Working/HomeGrownService/FjordMinutes/app/assets/config/manifest.js" these files were linked:
07:53:17 web.1  |   - /Users/kashiyamashintarou/Working/HomeGrownService/FjordMinutes/app/assets/stylesheets/application.css
07:53:17 web.1  |   - /Users/kashiyamashintarou/Working/HomeGrownService/FjordMinutes/app/assets/builds/application.css
07:53:17 web.1  | )
07:53:17 web.1  |   
07:53:17 web.1  | sprockets (4.2.1) lib/sprockets/base.rb:100:in `find_all_linked_assets'
07:53:17 web.1  | sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `each'
07:53:17 web.1  | sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `to_a'
07:53:17 web.1  | sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
07:53:17 web.1  | concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
07:53:17 web.1  | concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
07:53:17 web.1  | concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
07:53:17 web.1  | concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
07:53:17 web.1  | concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
07:53:17 web.1  | concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
07:53:17 web.1  | concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
07:53:17 web.1  | concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
07:53:17 web.1  | <internal:kernel>:187:in `loop'
07:53:17 web.1  | concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
07:53:17 web.1  | concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
07:53:17 web.1  | concurrent-ruby (1.3.4) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
07:53:17 web.1  | Started GET "/favicon.ico" for 127.0.0.1 at 2024-10-18 07:53:17 +0900
07:53:17 web.1  |   
07:53:17 web.1  | ActionController::RoutingError (No route matches [GET] "/favicon.ico"):

```

**Comment by Kassy0220** [comment]
該当のエラーは複数のapplication.cssが読み込まれていることが問題となっているため、それぞれのファイルを確認した。
`app/assets/builds/application.css`の中身は次のようになっていた。

```
/* node_modules/@uiw/react-markdown-preview/esm/styles/markdown.css */
@media (prefers-color-scheme: dark) {
  .wmde-markdown,
  .wmde-markdown-var {
    color-scheme: dark;
    --color-prettylights-syntax-comment: #8b949e;
```

どうやらこのファイルは、一時的にインストールしていたreact-markdown-previewパッケージにより生成されたもので、これが`app/assets/stylesheets/application.css`と被りエラーになっていた模様。

react-markdown-previewはすでに削除しているため、`app/assets/builds/application.css`も削除したところエラーが解消した。

開発環境のエラーを解消することができたので、このIssueをクローズします。
